export const SAVED = 'saved'
export const TAGGED = 'tagged'
export const POSTS = ''
export const FOLLOWERS = 'followers'
export const FOLLOWING = 'following'
export const POST = ':userPost'
export const SAVED_POSTS = ':savedPost'