export const ActionType = {
    SET_USER: 'SET_USER',
    SET_CURRENT_PROFILE_USER: 'SET_CURRENT_PROFILE_USER',
    SET_CHATS: 'SET_CHATS',
    SET_CURRENT_POST: 'SET_CURRENT_POST',
    SET_IS_LOADING: 'SET_IS_LOADING'
}